version: '3'

services:
  redis:
    image: redis:2.8
    expose:
      - "6379"
  rabbitmq:
    image: rabbitmq:3.7
    expose:
      - "5672"
  dataflow-server:
    image: tzolov/spring-cloud-dataflow-server-local:${DATAFLOW_VERSION}
    container_name: dataflow-server
    ports:
      - "9393:9393"
    environment:
      - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
    volumes:
      - ./apps:/apps
      - ./input:/input
      - ./output:/output
    depends_on:
      - rabbitmq
      - redis
  app-import:
    image: alpine:3.7
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        while ! nc -z dataflow-server 9393;
        do
          sleep 1;
        done;
        wget -qO- 'http://dataflow-server:9393/apps/sink/image-viewer' --post-data='uri=file:/apps/image-viewer-0.0.1-SNAPSHOT.jar';
        echo 'Image Viewer apps imported'
        wget -qO- 'http://dataflow-server:9393/apps/processor/pose-estimation' --post-data='uri=file:/apps/pose-estimation-processor-rabbit-2.0.1.BUILD-SNAPSHOT.jar&metadata-uri=file:/apps/pose-estimation-processor-rabbit-2.0.1.BUILD-SNAPSHOT-metadata.jar';
        echo 'Pose Estimation apps imported'
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Darwin.RELEASE/spring-cloud-stream-app-descriptor-Darwin.RELEASE.stream-apps-rabbit-maven';
        echo 'Stream apps imported'
        wget -qO- 'http://dataflow-server:9393/apps'  --post-data='uri=http://bit.ly/Clark-GA-task-applications-maven&force=true';
        echo 'Task apps imported'"
volumes:
  apps:
  input:
  output:
